# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2be59baadc2b57b9d9e3fc8349af8a61cdd300af7873dfb688431ed7c78180eaf0cf4edc379b3428f2492498a67a940a552574ed346cf5232e0ebe89fecb7cc9

test:
  secret_key_base: 57b4061243d4b1a63c9b726099af920ab6354f9b0d4417fc99b4b832aec52f7348cf0186a71003d75eba12a68307561dc5dd8863a2c7c01622d70b9a8fef3d31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
